language: node_js
node_js:
- node
notifications:
  email:
    on_success: always
    on_failure: always
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: elysium
  api_key:
    secure: G0R0wtcKpHAulOHuR6MAheGRl/rHGyo5mQhVAREyoa10nojye1pp/Zm9czmkrRvVgJR9ft6qMb8hB4hvHtjg1hKYpgAVSjE1OQHj/WOvrpedxd6LRlOTft8DQ/vfN5TaJ/ebLqSKk+1sNRWcC2ZvmOQk6btdddzMgi+Ufl5hDWjWB0KJQ4RqromKr2ZBCBVeFndMcFa5xMNmhcahqIuiQG+MMrkg90fCKt2o8eylMMwyP1p+wh34sYDFD+t2P0VIGpQSHoyFB9WZIBE4DT26nQB6sr01zq1DN5PZz7OzDtBFgK6ons2eXYmgZfQTuPk/15qTOgNftiN2q7cfnk7MLZ/LJBLQgKnLKwED3cnRxe3/O/qEvIkNRC2PzEzcR4Ay8lYMeO+rB5Ipx87hW3ynh0J1VuBf92xQFOnE3j36Bk700dVUe1eCb3bHTNN2+xGquyLj+dpaVnXmKO65H0+IL50No8CnWaQt17Kv3tChwYMfEjuQk9UKEFSYVu3kIc+y6laINZHkfh/RIbDU1sd/3wIL2yktaKanI8Vs4QjwTKaqErU7LhyG8gXM1yBoH5sh13EYiOWrZ9Ektp8x4/wud8ApBw1VPdgXp4xglEZAmjco0qir5lGwcAaDfTsd1yuuhr7LyQbgUi0kzeC8SHtOdbz1Yb+EqOfVnyWu4CV5110=
