language: node_js
node_js:
- node
notifications:
  email:
    on_success: always
    on_failure: always
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: elysium
  api_key:
    secure: G0R0wtcKpHAulOHuR6MAheGRl/rHGyo5mQhVAREyoa10nojye1pp/Zm9czmkrRvVgJR9ft6qMb8hB4hvHtjg1hKYpgAVSjE1OQHj/WOvrpedxd6LRlOTft8DQ/vfN5TaJ/ebLqSKk+1sNRWcC2ZvmOQk6btdddzMgi+Ufl5hDWjWB0KJQ4RqromKr2ZBCBVeFndMcFa5xMNmhcahqIuiQG+MMrkg90fCKt2o8eylMMwyP1p+wh34sYDFD+t2P0VIGpQSHoyFB9WZIBE4DT26nQB6sr01zq1DN5PZz7OzDtBFgK6ons2eXYmgZfQTuPk/15qTOgNftiN2q7cfnk7MLZ/LJBLQgKnLKwED3cnRxe3/O/qEvIkNRC2PzEzcR4Ay8lYMeO+rB5Ipx87hW3ynh0J1VuBf92xQFOnE3j36Bk700dVUe1eCb3bHTNN2+xGquyLj+dpaVnXmKO65H0+IL50No8CnWaQt17Kv3tChwYMfEjuQk9UKEFSYVu3kIc+y6laINZHkfh/RIbDU1sd/3wIL2yktaKanI8Vs4QjwTKaqErU7LhyG8gXM1yBoH5sh13EYiOWrZ9Ektp8x4/wud8ApBw1VPdgXp4xglEZAmjco0qir5lGwcAaDfTsd1yuuhr7LyQbgUi0kzeC8SHtOdbz1Yb+EqOfVnyWu4CV5110=
env:
  global:
  - secure: CMm9lJRiEiKO69FNEB3XB8yRDnThnxS+oUqBiwqFdJW8fGZtrOrFyAYBn9dSd11pXJ8u7QELAm1W2VGsSSyaU+TxXYbGarGtb9vXC3vG6vktbO70UpiAUtQHU+x3MFJtFsIUppiVFbEcS7oUEK8SMk3qLli8Dj9jLtXxhhYjBm86CtATFC0KqpS1jBCN5IvvyaueaxIjgQIVIv2aNOh2JJxqXmY12kHS7GFRsFG4OfNqTVjxkFDbXsmAGZnrFqgg7tBefzFZ/Mtr0TvaV7KYEzoOzrrPcsqcrIL8t3UO2aajdScWQFv5DDAly4l54gjqTbuZAT6VBxqjTA38ifL8TxRnqxlRZLc6QUwve9PTIe1SUSsttFNFhXcOHLtMefNhqShjGwaoJWLdY9K7tpb/Zbr5m8jfbDxZyI0rLd6MzJb3BAUGin/GKh2qM4uEXZZnM6Xa0dj+9P1PA9LtFkXu4pGrSusH2IOQcZhmfoecXOC8N+Rwo1Zi50pxQG3jlINWLDN1mF5R1Cn/u4qd7iwh6bTqOL1q8y7syGFKlDiIfkqhq9iD6y3mYHR0V4DbE4y9lw1KBGMsXnv6dbHI2LbKmGb8QZx9qacF/vz4wedl5HD/GPSoYqtUmgmZ9LzUyNLcZzlUlUftFRjKZGV0rzJvmXCQpX3W1a0ARuSRlMZs5r0=
  - secure: iqYkxHgxW+Pxcgbs/NdCyy3qC9yVlmOixK+zCRSJW+tKaYX0io1vN3M0E8HAXGH+C66k5B3sLyHH6C1fSxS6YHeUmemjmPd6nMiQ1SK12HJm+xZZABE+RTaDbxdKNW5x6ZajWaRwEPtChz03dG7ROdfvY3e4E0mxxGFFEtpA5CjZ72GDPJuXcqObHN4upMPDOFeYdlXtt7TYEPybAYtRuC9rbvJU7cmA//thEidX/EE6/xf9Cu+yseHVMaHGRKnXz2F8Ho8vmLd94eGBNFKF/HE3+MxEAuDHgO0+Y/tkdBUnb/KfV8vV7ptwkaQnYZFifY4Tn8MMYDW8fAicr4K9wKlNkn51vt63zImBNjBe4AxZ4dQoj3UWknVB/kwnKlLx5wsAgzIj40EJzIg1yoyK+NwiAi2iU0diO04BRubqp1B8gJ+BBQzF4XTEdjIwdVvr57HbggsYdGdsAB0EKoynynTgrbKqVVchfeiG8o97gjGaNrM5jb/IEShY5cT7LqFWpo9+k4IX7+TyOmqtWMFxUv+eCmuXBdnhIQ8iDlOFRQ6xIWAX/iCao9GiYdfsGJ1LvZIn5EbDoA4V+HQXIzUpR6/wszzLAXNLo4kUMVYqODFJjq2WWV2YTgb50bjEntXwO5GtdIouUjuc3XYiYjgx8zXXEy2n6Wyqs1DRf4wfTT4=
